# Generated by Django 4.0 on 2021-12-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_id', models.IntegerField()),
                ('book_author', models.CharField(max_length=100)),
                ('assigned', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
