# Generated by Django 4.0 on 2021-12-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_bookdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_No', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('started_date', models.DateField()),
            ],
        ),
    ]
