# Generated by Django 4.0 on 2021-12-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_consumerdetails_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=100)),
                ('Piece_Created', models.IntegerField()),
                ('Piece_Sold', models.IntegerField()),
                ('Out_Of_Stock', models.BooleanField()),
                ('In_Stock', models.BooleanField()),
            ],
        ),
    ]
