# Generated by Django 4.0 on 2021-12-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_iteminventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventory',
            name='In_Stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='iteminventory',
            name='Out_Of_Stock',
            field=models.BooleanField(default=False),
        ),
    ]
