# Generated by Django 4.0 on 2021-12-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_iteminventory_in_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('required_attendence', models.IntegerField()),
                ('present', models.IntegerField()),
                ('total_days', models.IntegerField()),
                ('allowed', models.BooleanField(default=False)),
                ('detained', models.BooleanField(default=False)),
            ],
        ),
    ]
